site_name: Quantum Analyzer
site_description: Modular, extensible code analysis toolkit for Python codebases
site_author: iDeaKz
site_url: https://ideakz.github.io/quantum-analyzer

repo_name: iDeaKz/quantum-analyzer
repo_url: https://github.com/iDeaKz/quantum-analyzer

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.snippets
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Usage: usage.md
  - Patterns: patterns.md
  - Configuration: configuration.md
  - Auto-Fix: auto-fix.md
  - API Reference: api.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - quantum_analyzer